### ISSUE TITLE
Token error with bigger project developer

### ISSUE THREAD

**Issue by tapestreamer** [thecodacus/lazy-dev#1]
I tried a couple small projects and they finished without errors. Bigger projects i.e more options and difficulty, get a token error during development of files.

![9F7C370F-4FD5-4A48-A1A7-8713D6AD12E6](https://github.com/thecodacus/lazy-dev/assets/11431099/16cd111c-5cc7-4225-b3ec-b946ab1eadd4)

I’ve seen this before and suggestions could be to add a small delay to calm the api requests and throw in a token calculator?

I hope this helps :)

**Comment by thecodacus** [comment]
yes its a known issue, the context length for the prompt is getting too long. need to find a way to reduce the context length with out removing important data

**Comment by thecodacus** [comment]
you can now use `-m gpt-3.5-turbo-16k` flag in the cli this will have 4 times more token limit 

also added support for context compression to fit more stuff in the context, check this commit 6365904
